# web server configuration
server:
 port: 8081
 servlet:
  context-path: /
 compression:
  enabled: true
 address: 0.0.0.0
 # application configuration
spring:
  jmx:
   enabled: true
   default-domain: jmxBootDemo
  main:
   allow-bean-definition-overriding: true
  datasource:
   driverClassName: com.mysql.cj.jdbc.Driver
   url: jdbc:mysql://localhost:3306/chapter14?serverTimezone=UTC
   username: root
   password: root
   hikari:
    maximum-pool-size: 25
  mvc:
   hiddenmethod:
    filter: # HTTP Method filter
     enabled: true
   # internationalization configuration
  thymeleaf:
   prefix: classpath:templates/
   suffix: .html
   mode: HTML
   cache: false
   check-template: false
   reactive:
    max-chunk-size: 8192
  servlet:
   multipart:
    enabled: true
    max-file-size: 10MB
    max-request-size: 12MB
  jpa:
   generate-ddl: false
   properties:
    hibernate:
     jdbc:
      batch_size: 10
      fetch_size: 30
      max_fetch_depth: 3
      show-sql: true
      format-sql: false
      use_sql_comments: false
      hbm2ddl:
       auto: none
  messages:
   basename: i18n/global
   encoding: UTF-8
   always-use-message-format: true
logging:
 pattern:
  console: "%-5level: %class{0} - %msg%n"
 level:
  root: INFO
  org.springframework.boot: DEBUG
  com.utk: INFO
management:
  server:
    port: 9091
  endpoints:
   web:
      exposure:
        include: "*"
      base-path: /monitoring
   jmx:
    domain: jmxBootDemo
    exposure:
     include: "*"